name: Opera VPN Screenshot with SeleniumBase

on:
  workflow_dispatch:

jobs:
  opera-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://deb.opera.com/archive.key | sudo apt-key add -
          echo "deb [arch=amd64] https://deb.opera.com/opera-stable/ stable non-free" | sudo tee /etc/apt/sources.list.d/opera-stable.list
          sudo apt-get update
          sudo apt-get install -y opera-stable xvfb
          pip install seleniumbase

      - name: Run SeleniumBase Opera VPN Screenshot
        env:
          DISPLAY: ":99"
        run: |
          Xvfb :99 -screen 0 1920x1080x24 &
          sleep 2
          pytest opera_vpn_screenshot.py --browser=opera --headless

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: opera-vpn-screenshot
          path: opera_vpn_screenshot.png
