name: Psiphon3 + SeleniumBase Screenshot on Windows

on:
  workflow_dispatch:

jobs:
  psiphon-windows-seleniumbase:
    runs-on: windows-latest
    steps:
      - name: Download Psiphon3.exe
        run: |
          Invoke-WebRequest -Uri "https://psiphon.ca/psiphon3.exe" -OutFile "$env:USERPROFILE\Desktop\psiphon3.exe"

      - name: Start Psiphon3.exe (background)
        run: |
          Start-Process -FilePath "$env:USERPROFILE\Desktop\psiphon3.exe"
        shell: pwsh

      - name: Wait for Psiphon to establish connection
        run: |
          Start-Sleep -Seconds 40

      - name: Set up Python and SeleniumBase
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install SeleniumBase and Chrome WebDriver
        run: |
          pip install seleniumbase
          seleniumbase install chromedriver

      - name: Take screenshot of https://ipleak.net/
        run: |
          python -c "
          import time
          from seleniumbase import Driver
          driver = Driver(browser='chrome', headless=True)
          driver.get('https://ipleak.net/')
          time.sleep(15)
          driver.save_screenshot('ipleak_screenshot.png')
          driver.quit()
          "
        shell: pwsh

      - name: Upload ipleak.net screenshot
        uses: actions/upload-artifact@v4
        with:
          name: ipleak-screenshot
          path: ipleak_screenshot.png
