name: Use Psiphon in GitHub Actions

on:
  workflow_dispatch:

jobs:
  psiphon-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download Psiphon Tunnel Core Binary
        run: |
          wget -O psiphon-tunnel-core-x86_64 "https://github.com/Psiphon-Labs/psiphon-tunnel-core-binaries/raw/master/linux/psiphon-tunnel-core-x86_64"
          chmod +x psiphon-tunnel-core-x86_64

      - name: Create Psiphon config
        run: |
          cat > psiphon.config <<EOF
          {
            "IsRunProxy": true,
            "LocalHttpProxyPort": 3128,
            "LocalSocksProxyPort": 1080
          }
          EOF

      - name: Start Psiphon and Wait for Connection
        run: |
          ./psiphon-tunnel-core-x86_64 -config psiphon.config > psiphon.log 2>&1 &
          sleep 30
          grep -i 'listening' psiphon.log || true

      - name: Test HTTP Proxy with curl
        run: |
          curl --proxy http://127.0.0.1:3128 https://api.ipify.org

      - name: Test SOCKS Proxy with curl
        run: |
          curl --socks5-hostname 127.0.0.1:1080 https://api.ipify.org

      - name: Upload Psiphon Log
        uses: actions/upload-artifact@v4
        with:
          name: psiphon-log
          path: psiphon.log
