name: OpenVPN Connect and Script

on: [workflow_dispatch]

jobs:
  run-openvpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn google-chrome-stable
        python -m pip install --upgrade pip wheel
        pip install seleniumbase pyautogui pymongo python-xlib
        seleniumbase install chromedriver
        
    - name: Run Opera VPN Python script
      run: |
        python3 opera_vpn_screenshot.py

    - name: Connect to random OpenVPN config
      shell: bash
      run: |
        # Find all .ovpn files in /etc/openvpn
        configs=(/etc/openvpn/*.ovpn)
        if [ ${#configs[@]} -eq 0 ]; then
          echo "No .ovpn configs found in /etc/openvpn"
          exit 1
        fi
        # Pick a random config
        config="${configs[RANDOM % ${#configs[@]}]}"
        echo "Connecting using $config"
        sudo openvpn --config "$config" --daemon
        # Wait a bit to establish connection
        sleep 20
        # Optionally, check VPN connection (print public IP)
        curl ifconfig.me || true
