name: Use XVPN in GitHub Actions

on:
  workflow_dispatch:

jobs:
  xvpn-job:
    runs-on: ubuntu-latest
    steps:
      - name: Download XVPN binary
        run: |
          wget -O xvpn_linux_amd64 "https://z3d9.com/4dzfjmwrjw/XVPN_1.4.1_5006_8c0edcef_2025-09-26-17-00-38/xvpn_linux_amd64"

      - name: Move XVPN to /usr/local/bin
        run: |
          sudo mv xvpn_linux_amd64 /usr/local/bin/xvpn

      - name: Add execute permissions to XVPN
        run: |
          sudo chmod a+x /usr/local/bin/xvpn

      - name: Connect with XVPN (defaults: Auto, Fastest Server)
        run: |
          sudo xvpn connect > xvpn.log 2>&1 &
          sleep 30

      - name: Check external IP (should be VPN)
        run: |
          curl -s https://ipinfo.io

      - name: Upload XVPN log
        uses: actions/upload-artifact@v4
        with:
          name: xvpn-log
          path: xvpn.log
