name: Run Psiphon3 on Windows and Check IP

on:
  workflow_dispatch:

jobs:
  psiphon-windows:
    runs-on: windows-latest
    steps:
      - name: Download Psiphon3.exe
        run: |
          Invoke-WebRequest -Uri "https://psiphon.ca/psiphon3.exe" -OutFile "$env:USERPROFILE\Desktop\psiphon3.exe"

      - name: Start Psiphon3.exe (background)
        run: |
          Start-Process -FilePath "$env:USERPROFILE\Desktop\psiphon3.exe"
        shell: pwsh

      - name: Wait for Psiphon to establish connection
        run: |
          Start-Sleep -Seconds 15

      - name: Install curl with Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Write-Host "Installing Chocolatey..."
            Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }
          choco install curl -y
        shell: pwsh

      - name: Check external IP using curl
        run: |
          curl https://ipinfo.io
        shell: pwsh
