name: OpenVPN Connect and Script

on: [workflow_dispatch]

jobs:
  run-openvpn:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openvpn google-chrome-stable
        python -m pip install --upgrade pip --ignore-installed
        pip install --upgrade pip --ignore-installed
        pip install --upgrade wheel --ignore-installed
        pip install --upgrade seleniumbase --ignore-installed
        pip install --upgrade pyautogui --ignore-installed
        pip install --upgrade pymongo --ignore-installed
        pip install --upgrade python-xlib --ignore-installed
        seleniumbase install chromedriver
        
    - name: Run Opera VPN Python script
      run: |
        sudo python3 opera_vpn_screenshot.py

    - name: Connect to random OpenVPN config
      shell: bash
      run: |
        # Look for configs in repo folder ./vpn-configs
        configs=(vpn-configs/*.ovpn)
        if [ ${#configs[@]} -eq 0 ]; then
          echo "No .ovpn configs found in ./vpn-configs"
          exit 1
        fi
    
        # Pick a random config
        config="${configs[RANDOM % ${#configs[@]}]}"
        echo "Connecting using $config"
    
        # OpenVPN still needs root to create tun device, so keep sudo here
        sudo openvpn --config "$config" --daemon
    
        # Wait a bit to establish connection
        sleep 20
    
        # Optionally, check VPN connection (print public IP)
        curl ifconfig.me || true

