name: Run Psiphon3 on Windows and Check IP

on:
  workflow_dispatch:

jobs:
  psiphon-windows:
    runs-on: windows-latest
    steps:
      - name: Download Psiphon3.exe
        run: |
          Invoke-WebRequest -Uri "https://psiphon.ca/psiphon3.exe" -OutFile "$env:USERPROFILE\Desktop\psiphon3.exe"

      - name: Start Psiphon3.exe (background)
        run: |
          Start-Process -FilePath "$env:USERPROFILE\Desktop\psiphon3.exe"
        shell: pwsh

      - name: Wait for Psiphon to establish connection
        run: |
          Start-Sleep -Seconds 40

      - name: Check external IP
        run: |
          Invoke-WebRequest -Uri "https://ipinfo.io" -UseBasicParsing | Select-Object -ExpandProperty Content
        shell: pwsh
