name: Use Psiphon in GitHub Actions

on:
  workflow_dispatch:

jobs:
  use-psiphon:
    runs-on: ubuntu-latest
    steps:
      - name: Download Psiphon binary
        run: |
          wget -O psiphon-tunnel-core.tar.gz "https://github.com/Psiphon-Labs/psiphon-tunnel-core-binaries/releases/latest/download/psiphon-tunnel-core-linux.tar.gz"
          tar xzf psiphon-tunnel-core.tar.gz
          chmod +x psiphon-tunnel-core

      - name: Start Psiphon (background)
        run: |
          ./psiphon-tunnel-core --format=json --local-http-proxy-port=3128 --local-socks-proxy-port=1080 > psiphon.log 2>&1 &
          sleep 20
          grep -i 'listening' psiphon.log || true
        # Wait time may need to be increased for first connection.

      - name: Test with curl through Psiphon HTTP proxy
        run: |
          curl --proxy http://127.0.0.1:3128 https://api.ipify.org

      - name: Test with curl through Psiphon SOCKS proxy
        run: |
          curl --socks5-hostname 127.0.0.1:1080 https://api.ipify.org

      - name: Upload Psiphon log (optional)
        uses: actions/upload-artifact@v4
        with:
          name: psiphon-log
          path: psiphon.log
